### ISSUE TITLE
Guzzle 6

### ISSUE THREAD

**Issue by melihovv** [aerisweather/GuzzleHttpMock#4]
Will there be support for Guzzle 6?

**Comment by djmattyg007** [comment]
Does anyone know how much work would be required to add support for Guzzle 6? I'd be willing to contribute.

**Comment by djmattyg007** [comment]
Actually it looks like guzzle 6 already supports this itself: http://docs.guzzlephp.org/en/latest/testing.html#mock-handler

**Comment by ghost** [comment]
Is this library still being maintained?

This library requires Guzzle `~5.0.0`, which excludes Guzzle 5.3.1. Guzzle before that version was not compatible with PHP 7.1.

I can imagine it would be a larger job to move to Guzzle 6, but can the version constraint at least be changed to `^5.0`?

**Comment by lreisoliveira** [comment]
same problem .. any answer?

**Comment by four43** [comment]
Hey all,

We aren't maintaining this library anymore. We previously used this project in a legacy project and have since migrated away from the stack for our current efforts. Please feel free to submit pull requests and we can try and review them and publish them. Otherwise a fork may be the best option. Sorry but we just don't have the resources to dedicate to this right now.

-Seth
AerisWeather

**Comment by lreisoliveira** [comment]
Thanks  AerisWeather for the attention

**Comment by ghost** [comment]
See https://github.com/systemhaus/GuzzleHttpMock - working with Guzzle 6.

@four43  Could we talk about taking over the repository, or at least deprecating the packagist package and suggesting us as a replacement?
